import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { shipporiMincho } from "../lib/fonts";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${shipporiMincho.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <p
          data-testid="japanese-font-test"
          className={shipporiMincho.className}
          style={{ padding: "1rem", fontSize: "1.5rem" }}
        >
          ある朝、桜が咲いた。
        </p>
      </body>
    </html>
  );
}
